[[inbounds]]
port = 8080.0
listen = "0.0.0.0"
protocol = "vmess"

  [inbounds.settings]

    [[inbounds.settings.clients]]
    id = "bf8ec758-c7be-4a9c-9ce8-d5a5f023ab51"
    alterId = 8.0

  [inbounds.streamSettings]
  network = "ws"

    [inbounds.streamSettings.wsSettings]
    path = "/ws"

[[outbounds]]
protocol = "freedom"

  [outbounds.settings]
